version: "3"
services:
  employee_mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: "employee_mongodb"
    ports:
      - 27017:27017
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  employee_kafka:
    image: wurstmeister/kafka
    container_name: "employee_kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "employee-events:1:1"